security:
  key: 338B027372E9FF641ED7F1708F633C05E9DFD8F9BD1775AC3BDE406A0D9B2444E450F7062E663B5C
es:
  tags:
    index: customertags
api:
  enableApi: true
# es 配置
elasticsearch:
  sniff: false
  # es 集群名称
  clusterName: Joesearch
  # es 集群节点
  clusterNodes:
    - 192.168.5.207:9300
hbase:
  config:
    hbase.zookeeper.quorum: node0.Joe1.com,node1.Joe1.com,node2.Joe1.com
    hbase.zookeeper.port: 2181
  tableName:
    updateTime: tags_update_timestamp